"""add image_url to events

Revision ID: 939c3bbbbafd
Revises: 814e8e068d0f
Create Date: 2026-01-20 21:25:35.445283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939c3bbbbafd'
down_revision: Union[str, Sequence[str], None] = '814e8e068d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_events_image_url'), 'events', ['image_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_image_url'), table_name='events')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
