version: "3.8"
services:
  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redispass"]
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
    ports:
      - "3309:3306"
