version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis_test
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    restart: always
